### ISSUE TITLE
Duplicate doc is lying

### ISSUE THREAD

**Issue by kitofr** [akvo/akvo-notifications#22]
Just came across this while skimming some code.

https://github.com/akvo/akvo-notifications/blob/develop/src/akvo/notifications/store_mem.clj#L58-L61

Looks like that doc is just a falsely duplicate from the function above.

**Comment by iperdomo** [comment]
Hi @kitofr thanks for your report. Notice that this code has not been being maintained (never went into production). It was an effort that might be retaken in the future.

**Comment by kitofr** [comment]
Yes i noticed that it wasn't "that" active ;)
